### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by user-lfdsystems** [lfdsystems/workflow-testing#34]
### DESCRIPTION

Description

---

### EXPECTED BEHAVIOUR

Expected Behaviour

---

### ACTUAL BEHAVIOUR

Actual Behaviour

---

### STEPS TO REPRODUCE

1. Step1
2. Step2
3. Step3

---

### BUG SCREENSHOT

Bug Screenshot

---

### BUG CODE OR LOGS

```VBA
Logs
```

---

**Comment by developer-lfdsystems** [comment]
This worked as expected.
